---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Project BlueSquid"
keywords:    "IOT, IIOT, Business Intelligence, BI, AI, Inteligencia Artificial"
description: "Un sistema completo de hardware y software para monitoreo y posterior Analisis de datos."
source_link: "https://www.mecatronica.pe"
favicon:     "img/project_bluesquid_icon.ico"
touch_icon:  "img/project_bluesquid.jpg"
google_analytics_key: UA-71804821-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

